name: My first workflow

on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: |
          echo "Hello, Welcome to my simple Action"
          echo "By Lee Gottlieb"
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List File
        run: ls
      
      - name: read file
        run: cat README.md

